apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: my_nginx
  template:
    metadata:
      labels:
        app_name: my_nginx
    spec:
      containers:
        - name: nginx-deployment-container
          image: nginx:latest
