apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: my_nginx_app
  template:
    metadata:
      labels:
        app_name: my_nginx_app
    spec:
      containers:
        - name: nginx-container-app
          image: nginx:latest
          env:
            - name: DATABASE_HOST
              value: "test database"
            - name: DATABASE_PASSWORD
              value: "test password"
