apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  labels:
    app_name: nginx-replica
spec:
  replicas: 4
  selector:
    matchLabels:
      app_name: nginx-app
  template:
    metadata:
      labels:
        app_name: nginx-app
    spec:
      containers:
        - image: nginx:latest
          name: nginx-container