apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: test
spec:
  selector:
    app_name: my_nginx_app
  ports:
    - targetPort: 80
      port: 8081
      protocol: TCP
  type: NodePortgit