apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app_name: nginx-app-1
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
