apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
spec:
  containers:
    - name: container-with-volume
      image: nginx:latest
      volumeMounts:
        - name: config-volume
          mountPath: /etc/cong
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map-wth-multiple-keys