apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-configmap
spec:
  containers:
    - name: container-with-multiple-configmap
      image: nginx:latest
      env:
        - name: MY_FIRST_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config-map-first
              key: my_key1
        - name: My_SECOND_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config-map-second
              key: LOG_LEVEL
